name = "DiagrammaticEquations.jl"
uuid = "b66562e1-fa90-4e8b-9505-c909188fab76"
license = "MIT"
authors = authors = [
  "James Fairbanks",
  "Andrew Baas",
  "Evan Patterson",
  "Luke Morris",
  "George Rauta",
]
version = "0.0.1"

[deps]
Catlab = "d3509f1a-f4fe-4f63-b9c2-a8cefdb22603"

[compat]
Catlab = "^0.14"
julia = "1.6"
