env:
  JULIA_VERSION: "1.10.2"
  JULIA_DEPOT_PATH: "$DEPOT"

steps:

  - label: ":sunrise: Good morning!"
    command: "echo 'Good morning!'"

  - label: ":hammer: Build Project"
    command: 
      - "module load julia"
      - "julia --project=docs --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.precompile()'"
         
  - wait 

  - label: ":scroll: Build docs"
    env:
      JULIA_PROJECT: "docs/"
    command:
      - "srun --cpus-per-task=16 --mem=64G --time=1:00:00 --output=.buildkite/build_%j.log --unbuffered .buildkite/jobscript.sh"

  - wait

