env:
  JULIA_VERSION: "1.10.2"
  JULIA_DEPOT_PATH: "$DEPOT"

steps:

  - label: ":arrow_down: Load AlgebraicJulia pipeline"
    command: |
      curl -s https://raw.githubusercontent.com/AlgebraicJulia/.github/buildkite/buildkite/pipeline.yml | buildkite-agent pipeline upload

  - label: ":wave: Testing that we may edit the pipeline!"
    command: |
      echo "hello!"

  - wait
